version: "3.0"
services:
  app:
    build:
      context: .
    container_name: nextjs
    expose:
      - "3000"  # HOST:CONTAINER
    environment:
      - NODE_ENV=production
      - PORT=3000
      

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
