version: "3.0"
services:
  app:
    build:
      context: .
      args:
        DATABASE_URL: "postgresql://postgres.brwtptcbsotobghzsjcw:Renato@96475870@aws-0-us-east-2.pooler.supabase.com:5432/postgres?pgbouncer=true&connection_limit=1"

    container_name: nextjs
    expose:
      - "3000"  # HOST:CONTAINER
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Banco de dados
      - DATABASE_URL=postgresql://postgres.brwtptcbsotobghzsjcw:Renato@96475870@aws-0-us-east-2.pooler.supabase.com:5432/postgres?pgbouncer=true&connection_limit=1
     
    restart: always
      

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443" # If using HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - app
    restart: always
