version: "3.0"
services:
  app:
    build:
      context: .
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
        ENDPOINT: $ENDPOINT
    container_name: nextjs
    expose:
      - "3000"  # HOST:CONTAINER
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GITHUB_TOKEN=$GITHUB_TOKEN
      - ENDPOINT=$ENDPOINT
    env_file:
      - /home/docker-app/.env
    restart: always
      

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443" # If using HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - app
    restart: always
